<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{$title}</title>

    <link rel="icon" href="{static_path}/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="{static_path}/favicon.ico" type="image/x-icon" />
    <link type="text/css" href="{static_path}/css/app.css" />
</head>
<body>
    <div class="article-list-container">
        <ul>
            {foreach $articles as $article}
            <li>
                <h3>{$article['title']}</h3>
                <p>{$article['content']}</p>
            </li>
            {/foreach}
        </ul>
    </div>
</body>
</html>